# Generated by Django 4.1 on 2022-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
