# Generated by Django 4.1 on 2022-09-08 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_salary_vacancy_company_vacancy_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='hourlyWage',
            fields=[
                ('amount', models.FloatField(blank=True, help_text='Salary', null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.FloatField(blank=True, help_text='Salary', null=True, unique=True),
        ),
    ]
