# Generated by Django 4.1 on 2022-09-08 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_hourlywage_alter_salary_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobType',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_type',
            field=models.ManyToManyField(blank=True, to='vacancies.jobtype'),
        ),
    ]
