# Generated by Django 4.1 on 2022-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_jobtype_vacancy_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlywage',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Salary', null=True, unique=True),
        ),
    ]
