# Generated by Django 4.1 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_hourlywage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hourlyWage',
            field=models.ManyToManyField(blank=True, to='vacancies.hourlywage'),
        ),
    ]
