# Generated by Django 4.1 on 2022-09-08 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancy_hourlywage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='vacancies.benefits'),
        ),
    ]
