# Generated by Django 4.1 on 2022-09-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_benefits_alter_vacancy_description_vacancy_benefits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefits',
            new_name='Benefit',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='benefits',
            new_name='benefit',
        ),
    ]
