# Generated by Django 4.1 on 2022-09-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_rename_benefits_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='key_duties',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill_and_exp',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
